### ISSUE TITLE
Environment and dependecy management - needs to be clearer

### ISSUE THREAD

**Issue by SamHollings** [NHSDigital/rap-community-of-practice#13]
In the "levels of RAP" people become confused by environment and dependency management -  we need to link to page which very clearly describe these, what the point of it is, and how they can know if they're meeting this requirement.

**Comment by SamHollings** [comment]
In backlog under issue https://nhsd-jira.digital.nhs.uk/browse/NV-1307

**Comment by harrietrs** [comment]
duplicated by https://github.com/NHSDigital/rap-community-of-practice/issues/11 @SamHollings
