### ISSUE TITLE
Signpost resources to ensure accessibility requirements are met

### ISSUE THREAD

**Issue by harrietrs** [NHSDigital/rap-community-of-practice#14]
This is most relevant for any outputs produced. See [guidance](https://www.gov.uk/guidance/publishing-accessible-documents).

As a starting point, the python visualisation guide should include tips on how to make visualisations more accessible:
* The Home Office has some posters on [accessible design](https://github.com/UKHomeOffice/posters/blob/master/accessibility/dos-donts/posters_en-UK/accessibility-posters-set.pdf)
* There are also countless online resources on accessibility relating to colour-blindness, visual impairments etc.

We should also consider including a note on accessibility in the design of RAP. A pipeline would be difficult to reproduce if a user could not access any part of the pipeline. This includes README files, as well as output types.

**Comment by SamHollings** [comment]
Added to backlog under issue https://nhsd-jira.digital.nhs.uk/browse/NV-1327
