### ISSUE TITLE
RAP Publishing Checks - Clarify what are credentials and secrets

### ISSUE THREAD

**Issue by goodyguts** [NHSDigital/rap-community-of-practice#18]
We've had some feedback that the part of the publishing checks that says "no credentials or secrets" is not clear, as analysts have not seen these terms before.

The following text might make things easier to understand:

Credentials or secrets are essentially passwords that computers use for encrypted communication or access to services. For example, with many APIs (like the Google Maps API) you must supply a credential code to access the service. Often times these codes look like long strange combinations of letters and numbers (l79sDgH9s...). We must not share our passwords publicly, so you should not commit credentials and secrets.

**Comment by SamHollings** [comment]
Created issue https://nhsd-jira.digital.nhs.uk/browse/NV-1328 on our backlog
