### ISSUE TITLE
dependency management "not possible in DAE"

### ISSUE THREAD

**Issue by SamHollings** [NHSDigital/rap-community-of-practice#19]
In [Levels of RAP](https://github.com/NHSDigital/rap-community-of-practice/blob/main/what-is-RAP.md#levels-of-rap) it say:
` Does your repo include dependency management? (i.e. requirements.txt or conda environment for RDS users. Not possible in DAE)`

It's not strictly true that this cannot be described for DAE - though it is more limited. One can describe the cluster used (runtime, libraries etc).

**Comment by SamHollings** [comment]
Added to backlog as issue https://nhsd-jira.digital.nhs.uk/browse/NV-1329

**Comment by harrietrs** [comment]
This will be fixed (although not explicitly addressed), in the upcoming [PR](https://github.com/NHSDigital/RAP_CoP_dev/pull/16) by removing reference to DAE until we produce specific materials.
