### ISSUE TITLE
Dead link

### ISSUE THREAD

**Issue by abbieprescott** [NHSDigital/rap-community-of-practice#24]
In the [notebooks_versus_ide_development.md](https://github.com/NHSDigital/rap-community-of-practice/blob/main/implementing_RAP/general_guidance/notebooks_versus_ide_development.md) file, the [Quality Assurance of Code for Analysis and Research](https://best-practice-and-impact.github.io/qa-of-code-guidance/core_programming.html?highlight=notebooks#notebooks) link does not work. Neither does the 'The ONS best-practice team list [some of the problems with notebooks](https://best-practice-and-impact.github.io/qa-of-code-guidance/core_programming.html)' link.

**Comment by abbieprescott** [comment]
Would [this](https://best-practice-and-impact.github.io/qa-of-code-guidance/modular_code.html?highlight=notebooks#:~:text=Think%20carefully%20about%20whether%20notebooks%20are%20a%20suitable%20way%20to%20organise%20your%20code%23) be a suitable replacement for both links?

**Comment by harrietrs** [comment]
That works Abbie

**Comment by SamHollings** [comment]
@harrietrs  @abbieprescott  has this been resolved?

**Comment by abbieprescott** [comment]
Resolved in pull request #30 on RAP CoP Dev repo
