### ISSUE TITLE
Pyspark guidance

### ISSUE THREAD

**Issue by SamHollings** [NHSDigital/rap-community-of-practice#29]
I'm not a fan of referring to it as a "flavour of python" (about PYspark page)

I think Pyspark should be contained underneath Python.

I also think it should make it clear that distribution of processing only occurs if its set up right - spark on a normal laptop will not be any more powerful than say pandas. On a big cluster in databricks is a different story.

I think this page might also need a reference to other python datastructures - and how there is a right tool for the right job.

**Comment by helrich** [comment]
closing as this is captured on another RAP COP dev issue
